###日志设置
logging:
  config: classpath:conf/logback-dev.xml

spring:
  freemarker:
    cache: false
  ###数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master: #数据源1
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/anyway?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
        username: root
        password: root1234
        initial-size: 10
        max-active: 100
        min-idle: 10
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      slave: #数据源2
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.9.182.175:3317/search?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
        username: user_search
        password: afctHgln
        initial-size: 5
        max-active: 50
        min-idle: 5
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      #WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        principal-session-name: USER_SESSION
        principal-cookie-name: USER_COOKIE
        profile-enable: true
      #StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        allow: 127.0.0.1
        deny: